import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/main/Sidebar/Sidebar";
import Topbar from "@/components/main/Topbar/Topbar";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

console.log("Playfair className:", playfair.className);
console.log("Inter className:", inter.className);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${inter.variable} antialiased dark flex h-screen overflow-hidden`}
      >
        <Sidebar />
        <main className="w-full flex flex-col overflow-auto">
          <Topbar />
          
          {children}
        </main>
      </body>
    </html>
  );
}
